knp_snappy:
    pdf:
        enabled:    true
        binary:     C:\Users\MSI\Downloads\wkhtmltox\bin\wkhtmltopdf.exe
        options:    []
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
